### ISSUE TITLE
release_deploy.cmd fails due to annotations javadoc generation issue

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/enceladus#2180]
## Describe the bug
When trying to release v 3.0.0 with `release_deploy.cmd`, the following problem appeared
```
<mypath>\enceladus\data-model\src\main\scala\za\co\absa\enceladus\model\backend\Reference.scala:27: error: annotation argument needs to be a constant; found: "{".+("\"collection\": \"dataset\",").+("\"name\": \"Test\",").+("\"version\": 4").+("}")
      "\"version\": 4" +
                       ^
...
```
This problem has not been revealed before while building the project otherwise.

## To Reproduce
Steps to reproduce the behavior OR commands run:
```shell
mvn install
cd data-model
mvn net.alchim31.maven:scala-maven-plugin:4.4.0:doc-jar
```

## Additional context
Clearly, this is caused by the unexpected format of the annotations introduced in #2178
