### PR TITLE
#1280 Make DAO a thin jar and move shading logic to 'spark-jobs'.

### PR DESCRIPTION
**Pull request by yruslan**

### CODE REVIEW

File: spark-jobs/pom.xml [hunk 1]
```diff
@@ -191,6 +190,20 @@
...
+                             If not shaded the following exception will be thrown:
+                               Caused by: java.lang.ClassNotFoundException: za.co.absa.atum.model.RunState
+	                           at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
+	                           ...
+	                           at com.fasterxml.jackson.module.scala.deser.EnumerationDeserializer.deserialize(EnumerationDeserializerModule.scala:40)
+                               java.lang.NoClassDefFoundError: com/fasterxml/jackson/datatype/jsr310/JavaTimeModule
+                        -->
+                        <relocation>
+                            <pattern>com.fasterxml.jackson</pattern>
+                            <shadedPattern>com.shaded.fasterxml.jackson</shadedPattern>
```
Comment (dk1844) [inline spark-jobs/pom.xml:204]: Maybe it does not matter here (moreover, if the purpose for relocation is only not to interfere), but usually, I find a good practice to prefix the newyl relocated package name by our own namespace (e.g. `za.co.absa.shaded.com.fasterxml.jackson`). This also has the benefit of minimizing the chance that another jar chose the same shaded location.

Comment (yruslan) [reply spark-jobs/pom.xml:204]: Good point! Will do

File: spark-jobs/pom.xml [hunk 2]
```diff
@@ -191,6 +190,20 @@
                             <exclude>net.jpountz.lz4:*</exclude>
                         </excludes>
                     </artifactSet>
+                    <relocations>
+                        <!-- This was introduced in #86 Set up Standardization and Conformance Menas auth.
```
Comment (benedeki) [inline spark-jobs/pom.xml:194]: Question: I like comments. Just wonder, if this is not too detailed explanation?

Comment (yruslan) [reply spark-jobs/pom.xml:194]: I don't mind removing it. It just took some time to find out why we are doing this relocation. I'm slightly inclined to keep it for the future maintainers but will remove it if you think this is too much 😄

Comment (benedeki) [reply spark-jobs/pom.xml:194]: I definitely like that it's explained why the relocation was added. Just found it untypical, compared to what we usually have, that it got down to the level of mentioning the exception class. Fine if it stays, we can always shorten the comment if future. in case it's found to be long. 😉
