### ISSUE TITLE
Can I use Hadoop 2.6??

### ISSUE THREAD

**Issue by Praveen456B** [AbsaOSS/enceladus#591]
This is not a bug, it's just question, I can see you are using Hadoop 2.7.7 version for this application, 
I have 2.6 version in my cloudera sandbox, Can I use 2.6 version only for running this application, is Hadoop 2.6 version compatable??

**Comment by GeorgiChochov** [comment]
Hi there! You may very well try, we use it with 2.7.x, so it's the version we are sure is supported and suggest to be used. Please do let us know if it works.

**Comment by Praveen456B** [comment]
Tried but its not working with hadoop2.6 version, getting an issues, need be change many things if we want to use hadoop2.6.

**Comment by lokm01** [comment]
> Tried but its not working with hadoop2.6 version, getting an issues, need be change many things if we want to use hadoop2.6.

Have you (re)built the project for the specific hadoop version?

**Comment by Praveen456B** [comment]
Yes rebuild after changing the hadoop version with 2.6  , getting below errors. 

C:\Users\C046436\spark_enclds\enceladus-develop\utils\src\main\scala\za\co\absa\enceladus\utils\fs\FileSystemVersionUtils.scala
Error:(18, 26) object fs is not a member of package org.apache.hadoop
import org.apache.hadoop.fs.{FileSystem, Path}
Error:(21, 26) object conf is not a member of package org.apache.hadoop
import org.apache.hadoop.conf.Configuration
Error:(29, 36) not found: type Configuration
class FileSystemVersionUtils(conf: Configuration) {
Error:(32, 20) not found: value FileSystem
  private val fs = FileSystem.get(conf)
Error:(39, 26) not found: type Path
  def splitUriPath(path: Path): (String, String) = {

Error:(22, 26) object conf is not a member of package org.apache.hadoop
import org.apache.hadoop.conf.Configuration
Error:(23, 26) object fs is not a member of package org.apache.hadoop
import org.apache.hadoop.fs.{FileSystem, Path}
Error:(81, 54) not found: type Configuration
  def getHadoopConfiguration(hadoopConfDir: String): Configuration = {
Error:(49, 20) not found: value FileSystem
    val distJars = FileSystem.get(SparkTestBase.getHadoopConfiguration(confDir)).listStatus(new Path(distJarsDir)).map(_.getPath)

**Comment by Zejnilovic** [comment]
Hi there, this is because Hadoop 2.6.X is missing libraries that we are using. Which means that, unfortunately, you will not be able to use Enceladus with Hadoop 2.6.X. Minimal version should be 2.7.

**Comment by GeorgiChochov** [comment]
I'm going to assume this question has been resolved. Thank you for bringing it up!
